[build]
  # Since this is a static site with just an index.html, we don't need a build command
  # The publish directory is the root directory
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
